In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/processed_data.csv")

print(df.head())

         Date Store ID Product ID     Category Region  Inventory Level  \
0  2022-01-01     S001      P0001    Groceries  North              231
1  2022-01-01     S001      P0002         Toys  South              204
2  2022-01-01     S001      P0003         Toys   West              102
3  2022-01-01     S001      P0004         Toys  North              469
4  2022-01-01     S001      P0005  Electronics   East              166

   Units Sold  Units Ordered  Demand Forecast  Price  Discount  \
0         127             55           135.47  33.50        20
1         150             66           144.04  63.01        20
2          65             51            74.02  27.99        10
3          61            164            62.18  32.72        10
4          14            135             9.26  73.64         0

  Weather Condition  Holiday/Promotion  Competitor Pricing Seasonality
0             Rainy                  0               29.69      Autumn
1             Sunny                  0               66.16      Autumn
2             Sunny                  1               31.32      Summer
3            Cloudy                  1               34.74      Autumn
4             Sunny                  0               68.95      Summer

In [ ]:
print("Shape of dataset:", df.shape)
print("\nColumns:")
print(df.columns)

Shape of dataset: (73100, 21)

Columns:
Index(['Date', 'Store ID', 'Product ID', 'Category', 'Region',
       'Inventory Level', 'Units Sold', 'Units Ordered', 'Demand Forecast',
       'Price', 'Discount', 'Weather Condition', 'Holiday/Promotion',
       'Competitor Pricing', 'Seasonality', 'day_name', 'month', 'is_weekend',
       'hour', 'original_price', 'time_adjusted_price'],
      dtype='object')

In [ ]:
df['Original_Price'] = df['Price']
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,...,Holiday/Promotion,Competitor Pricing,Seasonality,day_name,month,is_weekend,hour,original_price,time_adjusted_price,Original_Price
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,...,0,29.69,Autumn,Saturday,1,True,0,33.50,36.850,33.50
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,...,0,66.16,Autumn,Saturday,1,True,0,63.01,69.311,63.01
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,...,1,31.32,Summer,Saturday,1,True,0,27.99,30.789,27.99
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,...,1,34.74,Autumn,Saturday,1,True,0,32.72,35.992,32.72
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,...,0,68.95,Summer,Saturday,1,True,0,73.64,81.004,73.64

In [ ]:
df['Adjusted_Price'] = df['Price']
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,...,Competitor Pricing,Seasonality,day_name,month,is_weekend,hour,original_price,time_adjusted_price,Original_Price,Adjusted_Price
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,...,29.69,Autumn,Saturday,1,True,0,33.50,36.850,33.50,33.50
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,...,66.16,Autumn,Saturday,1,True,0,63.01,69.311,63.01,63.01
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,...,31.32,Summer,Saturday,1,True,0,27.99,30.789,27.99,27.99
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,...,34.74,Autumn,Saturday,1,True,0,32.72,35.992,32.72,32.72
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,...,68.95,Summer,Saturday,1,True,0,73.64,81.004,73.64,73.64

In [ ]:
df.loc[df['Demand Forecast'] > 120, 'Adjusted_Price'] *= 1.10
df.loc[df['Demand Forecast'] < 50, 'Adjusted_Price'] *= 0.95

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])
print(df.dtypes)

Date                   datetime64[ns]
Store ID                       object
Product ID                     object
Category                       object
Region                         object
Inventory Level                 int64
Units Sold                      int64
Units Ordered                   int64
Demand Forecast               float64
Price                         float64
Discount                        int64
Weather Condition              object
Holiday/Promotion               int64
Competitor Pricing            float64
Seasonality                    object
day_name                       object
month                           int32
is_weekend                       bool
hour                            int32
original_price                float64
time_adjusted_price           float64
Original_Price                float64
Adjusted_Price                float64
dtype: object

In [ ]:
df['day_name'] = df['Date'].dt.day_name()
df['month'] = df['Date'].dt.month
df['is_weekend'] = df['Date'].dt.weekday >= 5

df[['Date', 'day_name', 'month', 'is_weekend']].head()

        Date  day_name  month  is_weekend
0 2022-01-01  Saturday      1        True
1 2022-01-01  Saturday      1        True
2 2022-01-01  Saturday      1        True
3 2022-01-01  Saturday      1        True
4 2022-01-01  Saturday      1        True

In [ ]:
df['original revenue'] = df['Price'] * df['Units Sold']

In [ ]:
df['original_revenue'] = df['Price'] * df['Demand Forecast']

In [ ]:
# Calculate original revenue
df['original_revenue'] = df['Price'] * df['Demand Forecast']

# Display result
df[['Price','Demand Forecast','original_revenue']].head()

   Price  Demand Forecast  original_revenue
0  33.50           135.47         4538.2450
1  63.01           144.04         9075.9604
2  27.99            74.02         2071.8198
3  32.72            62.18         2034.5296
4  73.64             9.26          681.9064

In [ ]:
df['original_revenue'] = df['Price'] * df['Units Sold']
df[['Price', 'Units Sold', 'original_revenue']].head()

   Price  Units Sold  original_revenue
0  33.50         127           4254.50
1  63.01         150           9451.50
2  27.99          65           1819.35
3  32.72          61           1995.92
4  73.64          14           1030.96

In [ ]:
df['adjusted_price'] = df['Price']
df[['Price', 'adjusted_price']].head()

   Price  adjusted_price
0  33.50           33.50
1  63.01           63.01
2  27.99           27.99
3  32.72           32.72
4  73.64           73.64

In [ ]:
# Weekend price increase
df.loc[df['is_weekend'] == True, 'adjusted_price'] *= 1.10

# High-demand months price increase
df.loc[df['month'].isin([11, 12]), 'adjusted_price'] *= 1.12

# Low-demand months price decrease
df.loc[df['month'].isin([6, 7]), 'adjusted_price'] *= 0.95

df[['Date', 'Price', 'adjusted_price']].head(10)

        Date  Price  adjusted_price
0 2022-01-01  33.50         40.5350
1 2022-01-01  63.01         76.2421
2 2022-01-01  27.99         33.8679
3 2022-01-01  32.72         39.5912
4 2022-01-01  73.64         89.1044
5 2022-01-01  76.83         92.9643
6 2022-01-01  34.16         41.3336
7 2022-01-01  97.99        118.5679
8 2022-01-01  20.74         25.0954
9 2022-01-01  59.99         72.5879

In [ ]:
df['Original_Price'] = df['Price']
df['Adjusted_Price'] = df['Price']

df[['Price', 'Original_Price', 'Adjusted_Price']].head()

   Price  Original_Price  Adjusted_Price
0  33.50           33.50           33.50
1  63.01           63.01           63.01
2  27.99           27.99           27.99
3  32.72           32.72           32.72
4  73.64           73.64           73.64

In [ ]:
df.loc[df['Demand Forecast'] > 120, 'Adjusted_Price'] *= 1.10
df.loc[df['Demand Forecast'] < 50, 'Adjusted_Price'] *= 0.95

df[['Demand Forecast', 'Price', 'Adjusted_Price']].head()

   Demand Forecast  Price  Adjusted_Price
0           135.47  33.50          36.850
1           144.04  63.01          69.311
2            74.02  27.99          27.990
3            62.18  32.72          32.720
4             9.26  73.64          69.958

In [ ]:
df.loc[df['Seasonality'] == 'Summer', 'Adjusted_Price'] *= 1.08
df.loc[df['Seasonality'] == 'Winter', 'Adjusted_Price'] *= 1.05

df[['Seasonality', 'Price', 'Adjusted_Price']].head()

  Seasonality  Price  Adjusted_Price
0      Autumn  33.50        36.85000
1      Autumn  63.01        69.31100
2      Summer  27.99        30.22920
3      Autumn  32.72        32.72000
4      Summer  73.64        75.55464

In [ ]:
df.loc[df['Holiday/Promotion'] == 1, 'Adjusted_Price'] *= 1.07

df[['Holiday/Promotion', 'Price', 'Adjusted_Price']].head()

   Holiday/Promotion  Price  Adjusted_Price
0                  0  33.50       36.850000
1                  0  63.01       69.311000
2                  1  27.99       32.345244
3                  1  32.72       35.010400
4                  0  73.64       75.554640

In [ ]:
df.loc[df['Price'] < df['Competitor Pricing'], 'Adjusted_Price'] *= 1.05
df.loc[df['Price'] > df['Competitor Pricing'] + 10, 'Adjusted_Price'] *= 0.97

df[['Price', 'Competitor Pricing', 'Adjusted_Price']].head()

   Price  Competitor Pricing  Adjusted_Price
0  33.50               29.69       36.850000
1  63.01               66.16       72.776550
2  27.99               31.32       33.962506
3  32.72               34.74       36.760920
4  73.64               68.95       75.554640

In [ ]:
df['Adjusted_Price'] = df['Adjusted_Price'].round(2)

df[['Price', 'Adjusted_Price']].head()

   Price  Adjusted_Price
0  33.50           36.85
1  63.01           72.78
2  27.99           33.96
3  32.72           36.76
4  73.64           75.55

In [ ]:
df['Original_Revenue'] = df['Original_Price'] * df['Demand Forecast']

df[['Original_Price', 'Demand Forecast', 'Original_Revenue']].head()

   Original_Price  Demand Forecast  Original_Revenue
0           33.50           135.47         4538.2450
1           63.01           144.04         9075.9604
2           27.99            74.02         2071.8198
3           32.72            62.18         2034.5296
4           73.64             9.26          681.9064

In [ ]:
df['New_Revenue'] = df['Adjusted_Price'] * df['Demand Forecast']

df[['Adjusted_Price', 'Demand Forecast', 'New_Revenue']].head()

   Adjusted_Price  Demand Forecast  New_Revenue
0           36.85           135.47    4992.0695
1           72.78           144.04   10483.2312
2           33.96            74.02    2513.7192
3           36.76            62.18    2285.7368
4           75.55             9.26     699.5930

In [ ]:
df[['Price', 'Adjusted_Price', 'Demand Forecast', 'Original_Revenue', 'New_Revenue']].head(10)

   Price  Adjusted_Price  Demand Forecast  Original_Revenue  New_Revenue
0  33.50           36.85           135.47         4538.2450    4992.0695
1  63.01           72.78           144.04         9075.9604   10483.2312
2  27.99           33.96            74.02         2071.8198    2513.7192
3  32.72           36.76            62.18         2034.5296    2285.7368
4  73.64           75.55             9.26          681.9064     699.5930
5  76.83           99.70           139.82        10742.3706   13940.0540
6  34.16           40.30           108.92         3720.7072    4389.4760
7  97.99          113.18           329.73        32310.2427   37318.8414
8  20.74           22.81           174.15         3611.8710    3972.3615
9  59.99           67.23            24.47         1467.9553    1645.1181

In [ ]:
total_original_revenue = df['Original_Revenue'].sum()
total_new_revenue = df['New_Revenue'].sum()

print("Total Original Revenue:", round(total_original_revenue, 2))
print("Total New Revenue:", round(total_new_revenue, 2))

Total Original Revenue: 570417337.62
Total New Revenue: 672563702.6

In [ ]:
revenue_lift = ((total_new_revenue - total_original_revenue) / total_original_revenue) * 100
print("Revenue Lift (%):", round(revenue_lift, 2))

Revenue Lift (%): 17.91

In [ ]:
print("========== FINAL RESULTS ==========")
print("Original Revenue :", round(total_original_revenue, 2))
print("New Revenue      :", round(total_new_revenue, 2))
print("Revenue Lift %   :", round(revenue_lift, 2))

========== FINAL RESULTS ==========
Original Revenue : 570417337.62
New Revenue      : 672563702.6
Revenue Lift %   : 17.91

In [ ]:
df.to_csv('/content/pricing_engine_output.csv', index=False)
print("File saved successfully!")

File saved successfully!